import {
  Currency,
  CurrencyStatus,
  CurrencyType,
} from './schemas/currency.schema';

export const defaultCurrencies: Currency[] = [
  {
    name: 'Bitcoin',
    ticker: 'btc',
    status: CurrencyStatus.Active,
    type: CurrencyType.Crypto,
    isStable: false,
    image: 'https://www.countryflags.io/bt/flat/64.png',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Ethereum',
    ticker: 'eth',
    status: CurrencyStatus.Active,
    type: CurrencyType.Crypto,
    isStable: false,
    image: 'https://www.countryflags.io/et/flat/64.png',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Ripple',
    ticker: 'xrp',
    status: CurrencyStatus.Active,
    type: CurrencyType.Crypto,
    isStable: false,
    image: 'https://www.countryflags.io/rp/flat/64.png',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Binance Coin',
    ticker: 'bnb',
    status: CurrencyStatus.Active,
    type: CurrencyType.Crypto,
    isStable: false,
    image: 'https://www.countryflags.io/bn/flat/64.png',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'TRON',
    ticker: 'trx',
    status: CurrencyStatus.Active,
    type: CurrencyType.Crypto,
    isStable: false,
    image: 'https://www.countryflags.io/to/flat/64.png',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Shiba Inu',
    ticker: 'shib',
    status: CurrencyStatus.Active,
    type: CurrencyType.Crypto,
    isStable: false,
    image: 'https://www.countryflags.io/sb/flat/64.png',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Solana',
    ticker: 'sol',
    status: CurrencyStatus.Active,
    type: CurrencyType.Crypto,
    isStable: false,
    image: 'https://www.countryflags.io/sl/flat/64.png',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Polygon',
    ticker: 'matic',
    status: CurrencyStatus.Active,
    type: CurrencyType.Crypto,
    isStable: false,
    image: 'https://www.countryflags.io/mp/flat/64.png',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Tether',
    ticker: 'usdt',
    status: CurrencyStatus.Active,
    type: CurrencyType.Crypto,
    isStable: true,
    image: 'https://www.countryflags.io/us/flat/64.png',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'USD Coin',
    ticker: 'usdc',
    status: CurrencyStatus.Active,
    type: CurrencyType.Crypto,
    isStable: true,
    image: 'https://www.countryflags.io/us/flat/64.png',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Dai',
    ticker: 'dai',
    status: CurrencyStatus.Active,
    type: CurrencyType.Crypto,
    isStable: true,
    image: 'https://www.countryflags.io/da/flat/64.png',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'First Digital USD',
    ticker: 'fdusd',
    status: CurrencyStatus.Active,
    type: CurrencyType.Crypto,
    isStable: true,
    image: 'https://www.countryflags.io/fd/flat/64.png',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
